baseURL = "https://example.com"
title = "Johainworks"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "hugo.386"
preserveTaxonomyNames = true

tags = ["javascript", "typescript", "python", "csharp"]
categories = ["Menju"]

[params]
    mainpagetitle = "Johainworks"
    mainpagesubtitle = "hobbyist developer."
    mainpagedesc = "Greetings and welcome to my personal website. Here you can find information about my personal projects, update posts, and a page dedicated to telling you a bit about myself. Take a look around and let me know if you have any questions."
    copyrightname = "JM Fergeau"

    copyrighturl = "https://johain.works"
    showhugo = true

    twitter = "https://twitter.com/johainworks"
    github = "https://github.com/johainworks"
    gitlab = "https://gitlab.com/johainworks"

    loadfastload = false
    loadspeedfactor = 2.5
    loadonepass = true

[params.copyright]
    name = "Johainworks"
    url = "https://johain.works"
    prefix = "[Theme](https://gitlab.com/maxlefou/hugo.386)"
    suffix = "My personal website"

[menu]
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 1           # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/project/"
    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 3

[taxonomies]
  category = "categories"
  tag = "tags"

[privacy]

  [privacy.vimeo]
    disabled = true
    simple = true

  [privacy.twitter]
    disabled = true
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = true
    simple = true

  [privacy.youtube]
    disabled = true
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true